defaults: &defaults
  adapter:  mysql
  username: innotest_api
  password: inno_mysql  

  #encoding: utf8
  ## JRuby doesn't support socket:
   #socket: /var/run/mysqld/mysqld.sock

development:
  <<:       *defaults
  database: innotest_api
#  adapter: mysql
#  host: cogwisedb.crwdwnzqlaz3.us-east-1.rds.amazonaws.com
#  reconnect: false
#  database: chartered_production
#  username: cogwise
#  password: cg14ja28bdx

test:
  <<:       *defaults
  database: innotest_api

staging:
  <<:       *defaults
  database: innotest_api

production:
  <<:       *defaults
  database: innotest_api